const express=require('express');
const router=express.Router();
const userController=require('../controllers/users_controller');
router.get('/profile',userController.profile);
router.get('/login',userController.login);
router.get('/signup',userController.signUp);
router.post('/create',userController.create);
router.post('/create-session',userController.createSession);
router.post('/logout',userController.logout);
module.exports=router;